site_name: Matthew McKee
repo_url: https://github.com/MatthewMckee4/MatthewMckee4

nav:
  - Home:
      - About Me: index.md
      - Experience: experience.md
      - Personal Work: personal_work.md
      - Education: education.md

theme:
  name: material
  locale: en
  palette:
    scheme: slate
    primary: custom

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - content.tabs.link

  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css
